spring:
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: "1006gofgof!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
